<?php

namespace App\Enumerations\Penduduk;

use App\Traits\Enum\Finder;

enum Pekerjaan: string
{
    use Finder;

    case belum = 'BELUM/TIDAK BEKERJA';
    case mengurusRumahTangga = 'MENGURUS RUMAH TANGGA';
    case pelajar = 'PELAJAR/MAHASISWA';
    case pensiunan = 'PENSIUNAN';
    case asn = 'PEGAWAI NEGERI SIPIL';
    case tni = 'TENTARA NASIONAL INDONESIA';
    case polri = 'KEPOLISIAN RI;';
    case perdagangan = 'PERDAGANGAN';
    case petani = 'PETANI/PEKEBUN';
    case peternak = 'PETERNAK';
    case nelayan = 'NELAYAN/PERIKANAN';
    case industri = 'INDUSTRI';
    case konstruksi = 'KONSTRUKSI';
    case transportasi = 'TRANSPORTASI';
    case swasta = 'KARYAWAN SWASTA';
    case bumn = 'KARYAWAN BUMN';
    case bumd = 'KARYAWAN BUMD';
    case honorer = 'KARYAWAN HONORER';
    case buruhHarian = 'BURUH HARIAN LEPAS';
    case buruhTani = 'BURUH TANI/PERKEBUNAN';
    case buruhNelayan = 'BURUH NELAYAN/PERIKANAN';
    case buruhPeternakan = 'BURUH PETERNAKAN';
    case art = 'PEMBANTU RUMAH TANGGA';
    case tukangCukur = 'TUKANG CUKUR';
    case tukangListril = 'TUKANG LISTRIK';
    case tukangBatu = 'TUKANG BATU';
    case tukangKayu = 'TUKANG KAYU';
    case tukangSolSepatu = 'TUKANG SOL SEPATU';
    case pandaiBesi = 'TUKANG LAS/PANDAI BESI';
    case tukangJahit = 'TUKANG JAHIT';
    case tukangGigi = 'TUKANG GIGI';
    case penataRias = 'PENATA RIAS';
    case penataBusana = 'PENATA BUSANA';
    case penataRambut = 'PENATA RAMBUT';
    case mekanik = 'MEKANIK';
    case seniman = 'SENIMAN';
    case tabib = 'TABIB';
    case paraji = 'PARAJI';
    case perancangBusana = 'PERANCANG BUSANA';
    case penerjemah = 'PENTERJEMAH';
    case imamMasjid = 'IMAM MASJID';
    case pendeta = 'PENDETA';
    case pastor = 'PASTOR';
    case wartawan = 'WARTAWAN';
    case mubaligh = 'USTADZ/MUBALIGH';
    case juruMasak = 'JURU MASAK';
    case promotorAcara = 'PROMOTOR ACARA';
    case anggotaDPRRI = 'ANGGOTA DPR-RI';
    case anggotaDPD = 'ANGGOTA DPD';
    case anggotaBPK = 'ANGGOTA BPK';
    case presiden = 'PRESIDEN';
    case wakilPresiden = 'WAKIL PRESIDEN';
    case anggotaMK = 'ANGGOTA MAHKAMAH KONSTITUSI';
    case menteri = 'ANGGOTA KABINET KEMENTERIAN';
    case dubes = 'DUTA BESAR';
    case gubernur = 'GUBERNUR';
    case wakilGubernur = 'WAKIL GUBERNUR';
    case bupati = 'BUPATI';
    case wakilBupati = 'WAKIL BUPATI';
    case walikota = 'WALIKOTA';
    case wakilWlaikota = 'WAKIL WALIKOTA';
    case anggotaDPRDP = 'ANGGOTA DPRD PROVINSI';
    case anggotaDPRDK = 'ANGGOTA DPRD KABUPATEN/KOTA';
    case dosen = 'DOSEN';
    case guru = 'GURU';
    case pilot = 'PILOT';
    case pengacara = 'PENGACARA';
    case notaris = 'NOTARIS';
    case arsitek = 'ARSITEK';
    case beakuntanlum = 'AKUNTAN';
    case konsultan = 'KONSULTAN';
    case dokter = 'DOKTER';
    case bidan = 'BIDAN';
    case perawat = 'PERAWAT';
    case apoteker = 'APOTEKER';
    case psikiater = 'PSIKIATER/PSIKOLOG';
    case penyiarTV = 'PENYIAR TELEVISI';
    case penyiarRadio = 'PENYIAR RADIO';
    case pelaut = 'PELAUT';
    case peneliti = 'PENELITI';
    case sopir = 'SOPIR';
    case pialang = 'PIALANG';
    case paranormal = 'PARANORMAL';
    case pedagang = 'PEDAGANG';
    case perangkatDesa = 'PERANGKAT DESA';
    case kepalaDesa = 'KEPALA DESA';
    case biarawati = 'BIARAWATI';
    case wiraswasta = 'WIRASWASTA';
    case linnya = 'LAINNYA';
}
